---
server:
  port: 8085
spring:
  application:
    name: analysis-service
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     password: password
  # cache:
  # type: redis
  # TODO: рассмотреть возможность другой БД
  datasource:
    url:  jdbc:postgresql://${host-database}:5432/analysis_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    web: INFO
