server:
  port: 7777

spring:
  main:
    web-application-type:
      reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: mail-sender-service-route
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/*/*/*/mail-send, /*/*/*/mail-send/token
        - id: user-service-route
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{externalId}, /*/*/*/users/activation
        - id: project-service-route
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/*/*/*/projects, /*/*/*/projects/{externalId}
      default-filters:
        - name: AuthFilter
        - name: CircuitBreaker
          args:
            name: DefaultCircuitBreaker
            fallbackUri: forward:/fallback

  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            provider: custom-oidc
            scope: openid
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://127.0.0.1:7777/login/oauth2/code/custom-oidc"
        provider:
          custom-oidc:
            issuer-uri: "http://127.0.0.1:9000"
            token-uri: "http://127.0.0.1:9000/oauth2/token"
            authorization-uri: "http://127.0.0.1:9000/oauth2/authorize"
            jwk-set-uri: "http://127.0.0.1:9000/oauth2/jwks"
            user-info-uri: "http://127.0.0.1:9000/userinfo"

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

application:
  security:
    white-list:
      # users-api
      - url: /*/*/*/users
        methods: POST
      - url: /*/*/*/users/activation
        methods: POST
      - url: /*/*/*/users/*
        methods: POST

logging:
  level:
    org: INFO
