server:
  port: 7777
  host:
    url: http://127.0.0.1
  ms:
    api-gateway-url: ${server.host.url}:7777
    user-service-url: ${server.host.url}:8080
    project-service-url: ${server.host.url}:8082
    mail-sender-service-url: ${server.host.url}:8090
    auth-service-url: ${server.host.url}:9000

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: mail-sender-service-route
          uri: ${server.ms.mail-sender-service-url}
          predicates:
            - Path=/*/*/*/users/send/activation
        - id: user-service-route
          uri: ${server.ms.user-service-url}
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{externalId}, /*/*/*/users/activation
        - id: project-service-route
          uri: ${server.ms.project-service-url}
          predicates:
            - Path=/*/*/*/projects, /*/*/*/projects/{externalId}, /*/*/*/projects/**
      default-filters:
        - name: AuthFilter
        - name: CircuitBreaker
          args:
            name: DefaultCircuitBreaker
            fallbackUri: forward:/fallback
      globalcors:
        add-to-simple-url-handler-mapping: true
  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            provider: custom-oidc
            scope: openid
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: ${server.ms.api-gateway-url}/login/oauth2/code/custom-oidc
        provider:
          custom-oidc:
            issuer-uri: ${server.ms.auth-service-url}
            token-uri: ${server.ms.auth-service-url}/oauth2/token
            authorization-uri: ${server.ms.auth-service-url}/oauth2/authorize
            jwk-set-uri: ${server.ms.auth-service-url}/oauth2/jwks
            user-info-uri: ${server.ms.auth-service-url}/userinfo

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, prometheus

application:
  security:
    white-list:
      # users-api
      - url: /*
        methods: POST
      - url: /*/*/*/users
        methods: POST
      - url: /*/*/*/users/activation
        methods: POST, GET
      - url: /*/*/*/users/*
        methods: POST
      # mail sender
      - url: /*/*/*/users/send/activation
        methods: POST, GET

logging:
  level:
    org: INFO
