server:
  port: 7777

ms:
  frontend:
    url: ${microservices.frontend.url}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: mail-sender-service-route
          uri: ${microservices.mail-sender-service.url}
          predicates:
            - Path=/*/*/*/mail/send/activation

        - id: user-service-route
          uri: ${microservices.user-service.url}
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{externalId}, /*/*/*/users/activation

        - id: project-service-route
          uri: ${microservices.project-service.url}
          predicates:
            - Path=/*/*/*/projects, /*/*/*/projects/{externalId}, /*/*/*/projects/**

      default-filters:
        - name: AuthFilter
        - name: CircuitBreaker
          args:
            name: DefaultCircuitBreaker
            fallbackUri: forward:/fallback
      globalcors:
        add-to-simple-url-handler-mapping: true
  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            provider: custom-oidc
            scope: openid
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: ${microservices.api-gateway-service.url}/login/oauth2/code/custom-oidc
        provider:
          custom-oidc:
            issuer-uri: ${microservices.auth-service.url}
            token-uri: ${microservices.auth-service.url}/oauth2/token
            authorization-uri: ${microservices.auth-service.url}/oauth2/authorize
            jwk-set-uri: ${microservices.auth-service.url}/oauth2/jwks
            user-info-uri: ${microservices.auth-service.url}/userinfo

management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
  endpoint:
    health:
      show-details: always

application:
  security:
    white-list:
      - url: /*/*/*/users
        methods: POST
      - url: /*/*/*/users/activation
        methods: POST, GET
      - url: /*/*/*/mail/send/activation
        methods: POST

logging:
  level:
    org: INFO
