---
# host: 192.168.0.90
host: 192.168.0.90
host-url: http://${host}
lost-url: http://127.0.0.1
host-database: 192.168.0.90

services:
  frontend:
    url: ${host-url}:3000
  api: 
    url: ${lost-url}:7777
  mail:
    url: ${host-url}:8090
    config:
      url: ${host}
  user:
    url: ${lost-url}:8080
  project-service:
    url: ${lost-url}:8082
  auth: 
    url: ${host-url}:9000
