---
host: 192.168.0.90
host-url: http://${host}

services:
  frontend:
    url: localhost:3000
    # url: ${host-url}:3000
  api: 
    url: ${host-url}:7777
  mail:
    url: ${host-url}:8090
  user:
    url: ${host-url}:8080

microservices:
  frontend:
    url: ${host-url}:3000
  api-gateway-service:
    url: ${host-url}:7777
  user-service:
    url: ${host-url}:8080
  project-service:
    url: ${host-url}:8082
  mail-sender-service:
    url: ${host-url}:8090
  auth-service:
    url: ${host-url}:9000
datasource-config:
  project-service:
    url: jdbc:postgresql://${host}:5432/project_db
    username: user
    password: password
