---
host: 192.168.0.90
host-url: http://${host}
lost-url: http://127.0.0.1
host-database: 192.168.0.90

services:
  frontend:
    url: ${host-url}:3010
  api: 
    url: ${lost-url}:7777
  auth: 
    url: ${host-url}:9000
  user:
    url: ${lost-url}:8080
  project:
    url: ${lost-url}:8082
  analysis:
    url: ${lost-url}:8085
  bib-system:
    url: ${lost-url}:8086
  mail:
    url: ${host-url}:8090
    config:
      url: ${host}
