---
host-url: http://192.168.0.90

microservices:
  frontend:
    url: ${host-url}:3000
  api-gateway-service:
    url: ${host-url}:7777
  user-service:
    url: ${host-url}:8080
  project-service:
    url: ${host-url}:8082
  mail-sender-service:
    url: ${host-url}:8090
    mail-config:
      username: bibraryteka.sgu@gmail.com
      password: password
  auth-service:
    url: ${host-url}:9000
datasource-config:
  project-service:
    url: jdbc:postgresql://${host-url}:5432/project_db
    username: user
    password: password
  user-service:
    url: jdbc:postgresql://${host-url}:5432/user_db
    username: user
    password: password
