info:
  profile: github dev (updated 19.07.2023 19:32) ${TEST} - ${microservices.user-service.url}/private/api/v1

server:
  port: 9000

spring:
  application:
    name: authorization-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
  endpoint:
    health:
      show-details: always

app:
  security:
    client-settings:
      client-id: client
      client-secret: "{noop}secret"
      redirect-login-uri: ${microservices.api-gateway-service.url}/login/oauth2/code/custom-oidc
      redirect-success-login-uri: ${microservices.api-gateway-service.url}/authorized
    token-settings:
      access-token-life-time-in-minutes: 3600
      refresh-token-lifetime-in-minutes: 7200
    user-data-provider-url: ${microservices.user-service.url}/private/api/v1

logging:
  level:
    org: INFO
