server:
  port: 8090

spring:
  application:
    name: mail-sender-service

  mail:
    host: localhost
    port: 1025
    username: bibraryteka.sgu@gmail.com
    password: password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
  endpoint:
    health:
      show-details: always
