server:
  port: 8090

ms:
  api-gateway-service: ${microservices.api-gateway-service.url}/

spring:
  application:
    name: mail-sender-service

  mail:
    host: localhost
    port: 1025
    username: ${microservices.mail-sender-service.mail-config.username}
    password: ${microservices.mail-sender-service.mail-config.password}

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
  endpoint:
    health:
      show-details: always
