server:
  port: 8082

spring:
  application:
    name: project-service

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${microservices.auth-service.url}/oauth2/jwks

  data:
    redis:
      host: localhost
      port: 6379
      password: password

  cache:
    type: redis

  datasource:
    url: ${datasource-config.project-service.url}
    username: ${datasource-config.project-service.username}
    password: ${datasource-config.project-service.password}
    driver-class-name: org.postgresql.Driver

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    web: INFO
