server:
  port: 8082

spring:
  application:
    name: project-service

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks

  data:
    redis:
      host: localhost
      port: 6379
      password: password

  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://localhost:5432/project_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    web: INFO
