---
server:
  port: 8080
spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${services.auth.url}/oauth2/jwks
  datasource:
    url:  jdbc:postgresql://${host-database}:5432/user_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  # jackson:
    # auto-configure: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
app:
  validation:
    error-info:
      BLANK_FIRST_NAME_VALIDATION_ERROR_CODE: Firstname can not be blank
      BLANK_LAST_NAME_VALIDATION_ERROR_CODE: Lastname can not be blank
      BLANK_EMAIL_VALIDATION_ERROR_CODE: Email can not be blank
      BLANK_PASSWORD_VALIDATION_ERROR_CODE: Password can not be blank
      BLANK_PHONE_VALIDATION_ERROR_CODE: Phone can not be blank
      INCORRECT_FIRST_NAME_VALIDATION_ERROR_CODE: "Incorrect firstname format: %s"
      INCORRECT_LAST_NAME_VALIDATION_ERROR_CODE: "Incorrect lastname format: %s"
      INCORRECT_MIDDLE_NAME_VALIDATION_ERROR_CODE: "Incorrect middle name format: %s"
      INCORRECT_PHONE_VALIDATION_ERROR_CODE: "Incorrect format for phone number: %s"
      INCORRECT_EMAIL_VALIDATION_ERROR_CODE: "Incorrect email format: %s"
      INCORRECT_PASSWORD_VALIDATION_ERROR_CODE: "Incorrect password format: %s. The correct password should contain:[at least 1 uppercase letter, at least 1 lowercase letter, at least 1 number, at least 1 special character]. Minimum 8 characters and maximum 30 characters."
      INCORRECT_SEX_TYPE_ERROR_CODE: "Incorrect enum format: %s. Expected[MALE, FEMALE]"
  # patterns:
  #   email_pattern: ^[a-zA-Z0-9_!#$%&'+=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
  #   name_pattern: "[а-яА-Яa-zA-Z]{2,100}"
  #   phone_pattern: ((\\+7)|(\\+8)|[78])?((-\\d{3}-)|(\\(\\d{3}\\))|( \\d{3} )|(\\d{3}))\\d{3}[- ]?\\d{2}[- ]?\\d{2}
  #   grouped_phone_numbers_pattern: (\\d{1})(\\d{3})(\\d{3})(\\d{2})(\\d{2})
  #   password_pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,30}$
logging:
  level:
    web: INFO
